kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  labels:
    app: disk-filler
spec:
  storageClassName: px-csi-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi