
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pxbbq-web
  namespace: pxbbq
spec:
  replicas: {{ .Values.pxbbq.replicaCount }}
  selector:
    matchLabels:
      app: pxbbq-web
  template:
    metadata:
      labels:
        app: pxbbq-web
    spec:
      containers:
      - name: pxbbq-web
        image: {{ .Values.pxbbq.image }}
        env:
        - name: MONGO_INIT_USER
          value: {{ .Values.pxbbq.mongoUser }}
        - name: MONGO_INIT_PASS
          value: {{ .Values.pxbbq.mongoPassword }}
        - name: MONGO_NODES
          value: "mongo"
        - name: MONGO_PORT
          value: {{ .Values.pxbbq.mongoPort }}
        - name: MONGO_USER
          value: {{ .Values.pxbbq.mongoUser }}
        - name: MONGO_PASS
          value: {{ .Values.pxbbq.mongoPassword }}
        - name: CHATBOT_ENABLED
          value: {{ .Values.pxbbq.chatbotEnabled }}
        - name: PXBBQ_URI
          value: {{ .Values.pxbbq.pxbbqUri }}
        - name: MODEL_SERVER_URI
          value: {{ .Values.pxbbq.modelServerUri }}
        - name: NEO4J_URI
          value: {{ .Values.pxbbq.neo4jUri }}
        - name: ARCHIVE_ORDERS
          value: {{ .Values.pxbbq.archiveOrders }}
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 1
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      terminationGracePeriodSeconds: 0
